version: '2'
services:
  database:
    image: mysql:8.0.31-oracle
    container_name: rust_database
    environment:
      MYSQL_ROOT_PASSWORD: rustd4t4base
      MYSQL_DATABASE: diesel_demo
    volumes:
      - ./docker/database:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+07:00'
      ]